version: "1.0"
info:
  model: int-scaffold
packages:
- name: SuperIpaasProject
  gitServerName: SuperIpaasGitHub
  gitUrl: https://github.com/vikashsharma387/SuperIpaasProject
  gitUsername: vikashsharma387
  gitBranch: main
